# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MeInfoGram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MeInfoGram
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'MBProgressHUD'

  target 'MeInfoGramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MeInfoGramUITests' do
    # Pods for testing
  end

end
